#!/bin/sh

i=0

while [[ i -eq 0 ]]; do

  b=$(acpi | cut -d ' ' -f 4 | tr -d % | tr -d ,)
  echo $b

  if [[ $b -lt 21 ]]; then
    herbe "Battery $b%" &
  fi

  sleep 600 # 10 minutes

done

exit 0

